// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14ZC65QRjevAkCUPYP7QOOg-Zim0T5LE',
    appId: '1:907837107266:web:2b0407fd90a424cccd51db',
    messagingSenderId: '907837107266',
    projectId: 'chat-app-aa44c',
    authDomain: 'chat-app-aa44c.firebaseapp.com',
    storageBucket: 'chat-app-aa44c.firebasestorage.app',
    measurementId: 'G-CS8NEDQWLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKqzeessKELvi7QLhkqVo5n480AAItRPU',
    appId: '1:907837107266:android:9fc27619e7c25317cd51db',
    messagingSenderId: '907837107266',
    projectId: 'chat-app-aa44c',
    storageBucket: 'chat-app-aa44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTI10ke_AGFqf87k2AStlvgByqvMIxbso',
    appId: '1:907837107266:ios:96f4d4328e4ae0c0cd51db',
    messagingSenderId: '907837107266',
    projectId: 'chat-app-aa44c',
    storageBucket: 'chat-app-aa44c.firebasestorage.app',
    iosBundleId: 'com.example.sntegpito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTI10ke_AGFqf87k2AStlvgByqvMIxbso',
    appId: '1:907837107266:ios:96f4d4328e4ae0c0cd51db',
    messagingSenderId: '907837107266',
    projectId: 'chat-app-aa44c',
    storageBucket: 'chat-app-aa44c.firebasestorage.app',
    iosBundleId: 'com.example.sntegpito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB14ZC65QRjevAkCUPYP7QOOg-Zim0T5LE',
    appId: '1:907837107266:web:091409e7ee536747cd51db',
    messagingSenderId: '907837107266',
    projectId: 'chat-app-aa44c',
    authDomain: 'chat-app-aa44c.firebaseapp.com',
    storageBucket: 'chat-app-aa44c.firebasestorage.app',
    measurementId: 'G-41VD0S24C4',
  );
}
